learning_log/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('learning_logs.urls','learning_logs'))),
    path('users/',include(('users.urls','users')))
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url,re_path

from . import views

urlpatterns = [
    #主页
    re_path(r'^$',views.index,name = 'index'), # name为此条url的名字
    # 显示所有主题，主题页
    re_path(r'^topics/$',views.topics,name = 'topics'), # 同上
    # 特定主题的详细页面
    re_path('^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    # 用于用户添加新主题的网页
    re_path('^new_topic/$',views.new_topic,name='new_topic'),
    # 用于用户编写新条目的页面
    re_path('^new_entry/(?P<topic_id>\d+)$',views.new_entry,name='new_entry'),
    # 用于编辑条目的页面
    re_path('^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),
    re_path('^delete_entry/(?P<entry_id>\d+)/$',views.delete_entry,name='delete_entry'),
    re_path('^delete_topic/(?P<topic_id>\d+)/$',views.delete_topic,name='delete_topic'),
    re_path('^topics/my_topic/$',views.my_topic,name='my_topic'),
]

users/urls.py
from django.urls import re_path



from . import views
app_name = 'users'

urlpatterns = [
    re_path('^login/$',views.login_view,name='login'),
    re_path('^logout/$',views.logout_view,name='logout'),
    re_path('^register/$',views.register,name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    class Meta:
        db_table = 'topic'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
        db_table = 'entry'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text','public']
        labels = {'text':'','public':''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
# Create your views here.

from django.shortcuts import render,redirect,get_object_or_404
from .models import Topic,Entry
from django.urls import reverse
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

#在这里创建视图


def index(request):
    """学习笔记的主页"""

    return render(request,'learning_logs/index.html')


def check_topic_owner(topic, request):
    """判断主题的拥有者"""
    if topic.owner != request.user:
        raise Http404


def topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(public=True).order_by('date_added')
    return render(request,'learning_logs/topics.html',{'topics':topics})


def topic(request,topic_id):
    """单击单个主题显示所有条目"""
    topic = get_object_or_404(Topic,id=topic_id)
    # 检测请求主题是否私密，如果私密，判断是否请求者是拥有者
    if topic.public == False:
        check_topic_owner(topic,request)
    entries = topic.entry_set.order_by('-date_added')
    return render(request,'learning_logs/topic.html',{'topic':topic,'entries':entries})


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # post提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            form.save()
            return redirect('learning_logs:topics')

    return render(request,'learning_logs/new_topic.html',{'form':form})


@login_required
def new_entry(request,topic_id):
    """添加新条目"""
    topic = get_object_or_404(Topic,id=topic_id)
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EntryForm()
    else:
        # 用户提交了表单数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect(reverse('learning_logs:topic',args=[topic_id]))
    return render(request,'learning_logs/new_entry.html',{'topic':topic,'form':form})


@login_required
def edit_entry(request,entry_id):
    """编辑既有条目"""
    entry = get_object_or_404(Entry,id=entry_id)
    topic = entry.topic
    check_topic_owner(topic,request)
    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('learning_logs:topic',args=[topic.id]))
    return render(request,'learning_logs/edit_entry.html',{'entry':entry,'topic':topic,'form':form})


@login_required
def delete_entry(request,entry_id):
    """删除条目"""
    entry = get_object_or_404(Entry,id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)
    if request.method == 'POST':
        data = request.POST.get('choice')
        if data == '1':
            entry.delete()
            return redirect(reverse('learning_logs:topic',args=[topic.id]))
        else:
            return redirect(reverse('learning_logs:topic',args=[topic.id]))
    return render(request,'learning_logs/delete_entry.html',{'entry':entry})


@login_required
def delete_topic(request,topic_id):
    """删除主题"""
    topic = get_object_or_404(Topic,id=topic_id)
    check_topic_owner(topic, request)
    if request.method == 'POST':
        data = request.POST.get('choice')
        if data == '1':
            topic.delete()
            return redirect('learning_logs:topics')
        else:
            return redirect('learning_logs:topics')
    return render(request,'learning_logs/delete_topic.html',{'topic':topic})

@login_required
def my_topic(request):
    """个人主题中心"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    return render(request,'learning_logs/my_topic.html',{'topics':topics})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def login_view(request):
    """用户登录界面"""
    if request.method == 'POST':
        data = request.POST
        user = authenticate(username=data['username'],password=data['password'])
        if user:
            login(request,user)
            request.session.set_expiry(3600)
            return redirect('learning_logs:index')
        else:
            return render(request,'users/login.html',{'status':'用户名或密码有误，请重新输入！'})
    return render(request,'users/login.html')


def logout_view(request):
    """用户注销界面"""
    logout(request)
    return redirect("learning_logs:index")


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，并且定向到主页
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request,authenticated_user)
            return redirect('learning_logs:index')
        else:
            return render(request,'users/register.html',{'form':form})
    return render(request,'users/register.html',{'form':form})

templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,initial-scale=1">

      <title>PaperBook</title>
      {% bootstrap_css %}
      {% bootstrap_javascript %}
  </head>

  <body>
  <!--Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Paper Book</a>
        </div>

          <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'learning_logs:my_topic' %}">{{ user.username }}</a></li>
                  <li><a href="{% url 'users:logout' %}">log out</a></li>
                  {% else %}
                  <li><a href="{% url 'users:register' %}">register</a></li>
                  <li><a href="{% url 'users:login' %}">log in</a></li>
                  {% endif %}
              </ul>
          </div><!--/.nav-collapse -->
      </div>
  </nav>
  <div class="container">
      <div class="page-header">
          {% block header %}{% endblock header %}
      </div>
  <div>
      {% block content %}{% endblock content %}
  </div>

  </div> <!-- /contanier -->
  </body>
</html>

templates/learning_logs/delete_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h4>Are you sure you want to delete this entry?</h4>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:delete_entry' entry.id %}" method="POST">
    {% csrf_token %}

            <div class="radio">
                 <label>
                <input type="radio" name="choice" value="1">Yes
                 </label>
                <label>
                <input type="radio" name="choice" value="0">No
                 </label>
            </div>
    {% buttons%}
    <button name="submit">submit</button>
    {% endbuttons %}
    </form>
{% endblock content %}

templates/learning_logs/delete_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h4>Are you sure you want to delete this topic?</h4>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:delete_topic' topic.id %}" method="POST">
    {% csrf_token %}
            <div class="radio">
                 <label>
                <input type="radio" name="choice" value="1">Yes
                 </label>
                <label>
                <input type="radio" name="choice" value="0">No
                 </label>
            </div>
        {% buttons %}
    <button name="submit">submit</button>
    {% endbuttons %}
    </form>
{% endblock content %}

templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}
    <h4>Edit entry:</h4>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}"
          method="post" class="form">
          {% csrf_token %}
    {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primery">save changes</button>
      {% endbuttons %}
    </form>
{% endblock content %}

templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
<div class="jumbotron">
    <h1>Track your learning.</h1>
</div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your
    own Learning Log, and list the topics you're learning about.
</h2>
<h2>
Whereever you learning something new about a topic, make an entry
summarizing what you've learned.
</h2>
{% endblock content %}

{#</div>#}
{##}
{#{% block content %}#}
{#<p>Learning Log helps you keep track of your learning,for any topic#}
{#    you're leaning about.</p>#}
{#{% endblock content %}#}

templates/learning_logs/my_topic.html
{% extends "learning_logs/base.html" %}

  {% block header %}
      <h1>{{ user.username }}-Topics</h1>
  {% endblock header %}

{% block content %}
     <ul>
         {% for topic in topics %}
           <li>
           <h3>
               <a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
           </h3>
           </li>
         {% empty %}
           <li>
         No topics have been added yet.
           </li>
         {% endfor %}
     </ul>
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic.</a></h3>

{% endblock content %}

templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}
    <p><h4>Add a new entry:</h4></p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post"
      class="form">
            {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primery">add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% load bootstrap3 %}

{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}


    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
            {% csrf_token %}
    <div class="form-group">
        <label>
            <input type="text" class="form-row" name="text">
            </label>
    </div>
    <div class="radio">
        <label><input type="radio" name="public" value=1>Public</label>
        <label><input type="radio" name="public" value=0>Private</label>
    </div>
        {% buttons %}
        <button name="submit" class="btn btn-primery">add topic</button>
    {% endbuttons %}
    </form>
{% endblock content %}

templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>{{ topic }}</h2><p>
<a href="{% url 'learning_logs:delete_topic' topic.id %}">delete this topic</a>
</p>
{% endblock header %}

{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
        {% for entry in entries %}
            <div class="panel panel-default">
            <div class="panel-heading">

            <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                <a href="{% url 'learning_logs:delete_entry' entry.id %}"
                   style="margin-left:700px;">delete entry</a>
                </small>
            </h3>

            </div>
            <div class="panel-body">
               <h4>{{ entry.text|linebreaks }}</h4>
            </div>
            </div> <!-- panel -->
        {% empty %}
            <h4>There are no entries for this topic yet.</h4>
        {% endfor %}

{% endblock content %}

templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

  {% block header %}
      <h1>Topics</h1>
  {% endblock header %}

{% block content %}
     <ul>
         {% for topic in topics %}
           <li>
           {% if topic.public %}
           <h3>
               <a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
           </h3>
           {% endif %}
           </li>
         {% empty %}
           <li>
         No topics have been added yet.
           </li>
         {% endfor %}
     </ul>
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic.</a></h3>

{% endblock content %}

templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in your account.</h2>
{% endblock header %}

{% block content %}


    <form action="{% url 'users:login' %}" method="post" class="form">
    {% csrf_token %}

    <div class="form-group">
        <p>
            <label>
            Username:<input type="text" class="form-control" name="username">
            </label>
        </p>
    </div>

    <div class="form-group">
        <p>
            <label>
            Password:<input id="id_username" type="password" class="form-control" name="password">
            </label>
        </p>
    </div>

        {% buttons %}
        <button name="submit" class="btn btn-primery">log in</button>
        {% endbuttons %}
        <span style="color:red;"> {{ status }}</span>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}

templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Register a new account.</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'users:register' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primery">register</button>
        {% endbuttons %}
        <span style="color:red;"> {{ status }}</span>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}